### ISSUE TITLE
Possible bug in gbucket driver?

### ISSUE THREAD

**Issue by DocSavage** [janelia-flyem/dvid#266]
There was a rare dvid crash using gbucket.  Here's the little we had on the crash dump:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x90c643]

goroutine 12669550 [running]:
github.com/janelia-flyem/dvid/storage/gbucket.(*GBucket).getKeysInRangeRaw(0xc420362280, 0xe30860, 0xcaaa7ae558, 0xc48c7f93e0, 0x1c, 0x20, 0xc48c7f9400, 0x1c, 0x20, 0x0, ...)
    /groups/flyem/home/katzw/work/go/src/github.com/janelia-flyem/dvid/storage/gbucket/gbucket.go:1120 +0x1e3
github.com/janelia-flyem/dvid/storage/gbucket.(*GBucket).getKeysInRange(0xc420362280, 0xe30860, 0xcaaa7ae558, 0xca345a6390, 0xe, 0xe, 0xca345a63e0, 0xe, 0xe, 0x1, ...)
    /groups/flyem/home/katzw/work/go/src/github.com/janelia-flyem/dvid/storage/gbucket/gbucket.go:1163 +0x1a1
github.com/janelia-flyem/dvid/storage/gbucket.(*goBuffer).processRangeLocalResource(0xca83018200, 0xe30860, 0xcaaa7ae558, 0xca345a6390, 0xe, 0xe, 0xca345a63e0, 0xe, 0xe, 0xc51ed099a0, ...)
```

It refers to this line:
https://github.com/janelia-flyem/dvid/blob/master/storage/gbucket/gbucket.go#L1120

**Comment by stuarteberg** [comment]
I'm seeing something similar; not sure if it's the same bug.

Here's how to reproduce:

TOML (`ahrens-z1833b.toml`):
```toml
[server]
httpAddress = ":8000"
rpcAddress = ":8001"
webClient = "../dvid-distro/dvid-console"
instance_id_gen = "sequential"
instance_id_start = 100  # new ids start at least from this.

note = """
{"source": "gs://ahrens-z1833b-grayscale"}
"""

[logging]
logfile = "/tmp/dvid-logs/ahrens-z1833b-grayscale.log"
max_log_size = 500 # MB
max_log_age = 30   # days
[store]
    [store.mutable]
        engine = "gbucket"
        bucket= "ahrens-z1833b-grayscale"
```

Launch DVID:
`dvid -verbose serve ahrens-z1833b.toml`

Make a simple request:

```
curl 'http://127.0.0.1:8000/api/node/6a89/.meta/keys'
Internal Server Error
```


<details>

<summary>Click for panic log</summary>

```
Panic detected on request bergs-lm3/7wkhtSHT3c-000005:
runtime error: invalid memory address or nil pointer dereference
IP: 127.0.0.1:55479, URL: /api/node/6a89/.meta/keys
Stack trace:
goroutine 137 [running]:
github.com/janelia-flyem/dvid/server.recoverHandler.func1.1(0xc420386520, 0x1b, 0xc42016c700, 0x5744120, 0xc4202b7800)
	/magnetic/workspace/gopath/src/github.com/janelia-flyem/dvid/server/web.go:707 +0xc2
panic(0x4877760, 0x4e877e0)
	/miniforge/envs/flyem-forge/go/src/runtime/panic.go:505 +0x229
github.com/janelia-flyem/dvid/storage/gbucket.(*GBucket).getKeysInRangeRaw(0xc420314200, 0x4a72220, 0xc4200dc360, 0xc420384330, 0x10, 0x10, 0xc420384350, 0x10, 0x10, 0x0, ...)
	/magnetic/workspace/gopath/src/github.com/janelia-flyem/dvid/storage/gbucket/gbucket.go:1120 +0x1e3
github.com/janelia-flyem/dvid/storage/gbucket.(*GBucket).getKeysInRange(0xc420314200, 0x4a72220, 0xc4200dc360, 0xc42038431a, 0x2, 0x2, 0xc42038431c, 0x2, 0x2, 0x5784200, ...)
	/magnetic/workspace/gopath/src/github.com/janelia-flyem/dvid/storage/gbucket/gbucket.go:1163 +0x1a1
github.com/janelia-flyem/dvid/storage/gbucket.(*GBucket).KeysInRange(0xc420314200, 0x4a72220, 0xc4200dc360, 0xc42038431a, 0x2, 0x2, 0xc42038431c, 0x2, 0x2, 0x5, ...)
	/magnetic/workspace/gopath/src/github.com/janelia-flyem/dvid/storage/gbucket/gbucket.go:1598 +0xbf
github.com/janelia-flyem/dvid/datatype/keyvalue.(*Data).GetKeys(0xc420340828, 0x4a72220, 0xc4200dc360, 0x4, 0x1, 0x4, 0x4, 0x0)
	/magnetic/workspace/gopath/src/github.com/janelia-flyem/dvid/datatype/keyvalue/keyvalue.go:304 +0x12f
github.com/janelia-flyem/dvid/datatype/keyvalue.(*Data).ServeHTTP(0xc420340828, 0xc4206a3b80, 0x20, 0xc4200dc360, 0x5744120, 0xc4202b7800, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/janelia-flyem/dvid/datatype/keyvalue/keyvalue.go:470 +0x1790
github.com/janelia-flyem/dvid/server.instanceSelector.func1(0x5744120, 0xc4202b7800, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/janelia-flyem/dvid/server/web.go:970 +0x53e
net/http.HandlerFunc.ServeHTTP(0xc4203a4410, 0x5744120, 0xc4202b7800, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:1947 +0x44
github.com/janelia-flyem/dvid/server.repoRawSelector.func1(0x5744120, 0xc4202b7800, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/janelia-flyem/dvid/server/web.go:811 +0x38a
net/http.HandlerFunc.ServeHTTP(0xc4202a7820, 0x5744120, 0xc4202b7800, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:1947 +0x44
github.com/zenazn/goji/web.(*cStack).ServeHTTPC(0xc4202e0cc0, 0xc4202e0c30, 0xc4202e0c00, 0x5744120, 0xc4202b7800, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/middleware.go:50 +0x77
github.com/zenazn/goji/web.(*Mux).ServeHTTPC(0xc4210703f0, 0xc4202e0c30, 0xc4202e0c00, 0x5744120, 0xc4202b7800, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/mux.go:53 +0x76
github.com/zenazn/goji/web.(*router).route(0xc4210700a8, 0xc4202e0150, 0x5744120, 0xc4202b7800, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/router.go:119 +0x7b
github.com/zenazn/goji/web.(*mStack).newStack.func1(0x5744120, 0xc4202b7800, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/middleware.go:88 +0x56
net/http.HandlerFunc.ServeHTTP(0xc4200e2120, 0x5744120, 0xc4202b7800, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:1947 +0x44
github.com/janelia-flyem/dvid/server.corsHandler.func1(0x5744120, 0xc4202b7800, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/janelia-flyem/dvid/server/web.go:788 +0xb1
net/http.HandlerFunc.ServeHTTP(0xc4200e2240, 0x5744120, 0xc4202b7800, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:1947 +0x44
github.com/janelia-flyem/dvid/server.recoverHandler.func1(0x5744120, 0xc4202b7800, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/janelia-flyem/dvid/server/web.go:723 +0xbe
net/http.HandlerFunc.ServeHTTP(0xc4202a6f60, 0x5744120, 0xc4202b7800, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:1947 +0x44
github.com/janelia-flyem/dvid/server.httpAvailHandler.func1(0x5744120, 0xc4202b7800, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/janelia-flyem/dvid/server/web.go:693 +0x90
net/http.HandlerFunc.ServeHTTP(0xc4202a6f80, 0x5744120, 0xc4202b7800, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:1947 +0x44
github.com/zenazn/goji/web/middleware.AutomaticOptions.func1(0x5744120, 0xc4202b7800, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/middleware/options.go:70 +0x8d
net/http.HandlerFunc.ServeHTTP(0xc4202a7060, 0x5744120, 0xc4202b7800, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:1947 +0x44
github.com/zenazn/goji/web/middleware.Logger.func1(0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/middleware/logger.go:35 +0x2b6
net/http.HandlerFunc.ServeHTTP(0xc4202a7160, 0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:1947 +0x44
github.com/zenazn/goji/web.(*cStack).ServeHTTPC(0xc4202e0150, 0xc4202e0c30, 0xc4202e0c00, 0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/middleware.go:50 +0x77
github.com/zenazn/goji/web.(*Mux).ServeHTTPC(0xc421070070, 0xc4202e0c30, 0xc4202e0c00, 0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/mux.go:53 +0x76
github.com/zenazn/goji/web.(*router).route(0xc42024e6c8, 0xc4202e00c0, 0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/router.go:119 +0x7b
github.com/zenazn/goji/web.(*mStack).newStack.func1(0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/middleware.go:88 +0x56
net/http.HandlerFunc.ServeHTTP(0xc4200e20e0, 0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:1947 +0x44
github.com/zenazn/goji/web/middleware.RequestID.func1(0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/middleware/request_id.go:68 +0x20c
net/http.HandlerFunc.ServeHTTP(0xc4200e2100, 0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:1947 +0x44
github.com/zenazn/goji/web.(*cStack).ServeHTTP(0xc4202e00c0, 0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/middleware.go:46 +0x68
github.com/zenazn/goji/web.(*Mux).ServeHTTP(0xc42024e690, 0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/magnetic/workspace/gopath/src/github.com/zenazn/goji/web/mux.go:45 +0x5e
net/http.(*ServeMux).ServeHTTP(0x4e99e00, 0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:2337 +0x130
net/http.serverHandler.ServeHTTP(0xc4210b8000, 0x4a6d260, 0xc4203a80e0, 0xc42016c700)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4204092c0, 0x4a6dda0, 0xc4202b76c0)
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/miniforge/envs/flyem-forge/go/src/net/http/server.go:2795 +0x27b
```

</details>

**Comment by stuarteberg** [comment]
cc: @stephenplaza
