### ISSUE TITLE
repo deletion causes panic

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#331]
I have a test server with a lot of repos I want to delete.  I tried this:

```
dvid repos delete 0934100ae0e346a0a955aa66efe1b32a
```

which resulted in this error:
```
2019/11/10 23:09:44 gorpc.Client: [localhost:8001]. Cannot decode response: [unexpected EOF]
RPC error for "repos delete 0934100ae0e346a0a955aa66efe1b32a": gorpc.Client: [localhost:8001]. Cannot decode response: [unexpected EOF]
```

The dvid process stdout indicates that a panic occurred:

<details>

<summary>panic log</summary>

```
fatal error: sync: Unlock of unlocked RWMutex

goroutine 157 [running]:
runtime.throw(0x4c04454, 0x20)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/runtime/panic.go:617 +0x72 fp=0xc001164fc8 sp=0xc001164f98 pc=0x402ecc2
sync.throw(0x4c04454, 0x20)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/runtime/panic.go:603 +0x35 fp=0xc001164fe8 sp=0xc001164fc8 pc=0x402ec45
sync.(*RWMutex).Unlock(0xc0004a2700)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/sync/rwmutex.go:124 +0xa2 fp=0xc001165018 sp=0xc001164fe8 pc=0x40733f2
github.com/janelia-flyem/dvid/datastore.(*repoManager).deleteRepo(0xc0001004d0, 0xc00003bdc0, 0x20, 0x0, 0x0, 0x1d, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/datastore/repo_local.go:922 +0x227 fp=0xc0011651c8 sp=0xc001165018 pc=0x46c4f67
github.com/janelia-flyem/dvid/datastore.DeleteRepo(...)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/datastore/datastore.go:114
github.com/janelia-flyem/dvid/server.handleCommand(0xc0004da570, 0xc000dd26e0, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/server/rpc.go:325 +0x558e fp=0xc0011659c0 sp=0xc0011651c8 pc=0x4703bfe
runtime.call32(0xc000be9380, 0x4c6b548, 0xc000454d40, 0x800000020)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/runtime/asm_amd64.s:519 +0x3b fp=0xc0011659f0 sp=0xc0011659c0 pc=0x405a79b
reflect.Value.call(0x4a883c0, 0x4c6b548, 0x13, 0x4bea7b5, 0x4, 0xc000454d20, 0x1, 0x1, 0x4be1a80, 0xc000c45601, ...)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/reflect/value.go:447 +0x461 fp=0xc001165c10 sp=0xc0011659f0 pc=0x4085b61
reflect.Value.Call(0x4a883c0, 0x4c6b548, 0x13, 0xc000454d20, 0x1, 0x1, 0xc000454d00, 0x2, 0x2)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/reflect/value.go:308 +0xa4 fp=0xc001165c78 sp=0xc001165c10 pc=0x40855e4
github.com/valyala/gorpc.dispatchRequest(0xc000c65980, 0xc0005a4050, 0xb, 0xc00057a580, 0xc000d10e40)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/dispatcher.go:388 +0x273 fp=0xc001165de8 sp=0xc001165c78 pc=0x46791d3
github.com/valyala/gorpc.(*Dispatcher).NewHandlerFunc.func1(0xc0005a4050, 0xb, 0x4a26620, 0xc00057a580, 0xc0005a4050, 0xb)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/dispatcher.go:322 +0x63 fp=0xc001165e30 sp=0xc001165de8 pc=0x467eec3
github.com/valyala/gorpc.callHandlerWithRecover(0x4c6b490, 0xc000c6db10, 0xc0005a4050, 0xb, 0xc0000c69a0, 0x5, 0x4a26620, 0xc00057a580, 0x0, 0x0, ...)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:410 +0xc6 fp=0xc001165e80 sp=0xc001165e30 pc=0x467dc46
github.com/valyala/gorpc.serveRequest(0xc000959b20, 0xc000dbc000, 0xc000038180, 0xc00075c410, 0xc000db4240)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:379 +0x1ae fp=0xc001165fb8 sp=0xc001165e80 pc=0x467d88e
runtime.goexit()
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc001165fc0 sp=0xc001165fb8 pc=0x405c491
created by github.com/valyala/gorpc.serverReader
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:360 +0x171

goroutine 1 [chan receive]:
github.com/janelia-flyem/dvid/server.Serve()
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/server/server_local.go:509 +0x38f
main.DoServe(0xc000032040, 0x2, 0x2, 0x5, 0x4bea0e6)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/cmd/dvid/main.go:329 +0x7af
main.DoCommand(0xc000032040, 0x2, 0x2, 0x5, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/cmd/dvid/main.go:212 +0x3cd
main.main()
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/cmd/dvid/main.go:196 +0x2c2

goroutine 3 [syscall]:
os/signal.signal_recv(0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 35 [chan receive]:
github.com/janelia-flyem/dvid/dvid.init.0.func1()
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/dvid/distributed.go:37 +0x46
created by github.com/janelia-flyem/dvid/dvid.init.0
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/dvid/distributed.go:35 +0x63

goroutine 36 [chan receive]:
github.com/janelia-flyem/dvid/dvid.init.4.func1()
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/dvid/log.go:44 +0x86
created by github.com/janelia-flyem/dvid/dvid.init.4
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/dvid/log.go:43 +0x6a

goroutine 37 [select]:
github.com/janelia-flyem/dvid/storage.loadMonitor()
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/storage/monitor.go:81 +0x1a6
created by github.com/janelia-flyem/dvid/storage.init.2
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/storage/monitor.go:74 +0x15d

goroutine 20 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00025c5f0)
	/miniforge/conda-bld/dvid_1559799187361/work/src/go.opencensus.io/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
	/miniforge/conda-bld/dvid_1559799187361/work/src/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 21 [runnable]:
github.com/janelia-flyem/dvid/server.init.1.func1(0xc0000a8ae0, 0xc0000c6960)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/server/server.go:133 +0x38
created by github.com/janelia-flyem/dvid/server.init.1
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/server/server.go:131 +0x164

goroutine 22 [select]:
github.com/janelia-flyem/dvid/server.init.1.func2()
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/server/server.go:150 +0xbf
created by github.com/janelia-flyem/dvid/server.init.1
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/server/server.go:147 +0x17c

goroutine 50 [select]:
github.com/janelia-flyem/go/profiler.init.0.func1()
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/go/profiler/web_endpoints.go:59 +0x10a
created by github.com/janelia-flyem/go/profiler.init.0
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/go/profiler/web_endpoints.go:48 +0x95

goroutine 51 [chan receive]:
main.DoServe.func1(0xc000460120)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/cmd/dvid/main.go:251 +0x62
created by main.DoServe
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/cmd/dvid/main.go:250 +0x70

goroutine 207 [runnable]:
github.com/janelia-flyem/dvid/datastore.(*repoManager).deleteRepo.func1(0x4dd0b80, 0xc0006eb4f8)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/datastore/repo_local.go:916
created by github.com/janelia-flyem/dvid/datastore.(*repoManager).deleteRepo
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/datastore/repo_local.go:916 +0x1fa

goroutine 204 [IO wait]:
internal/poll.runtime_pollWait(0xa260c38, 0x72, 0xffffffffffffffff)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0011e3198, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0011e3180, 0xc000692000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_unix.go:169 +0x1f2
net.(*netFD).Read(0xc0011e3180, 0xc000692000, 0x1000, 0x1000, 0xc00004a500, 0xc000107c40, 0x42d1a2a)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000dda3f8, 0xc000692000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/net.go:177 +0x69
net/http.(*connReader).Read(0xc00046e4e0, 0xc000692000, 0x1000, 0x1000, 0x971003f59f, 0x55610a0, 0x72)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/http/server.go:787 +0x107
bufio.(*Reader).fill(0xc0000e2180)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc0000e2180, 0x4, 0x971003f59f, 0x55610a0, 0x0, 0x0, 0x55610a0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/bufio/bufio.go:138 +0x4f
net/http.(*conn).serve(0xc0000e6aa0, 0x4dbb5c0, 0xc0005b4000)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/http/server.go:1903 +0x9bf
created by net/http.(*Server).Serve
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/http/server.go:2884 +0x2f4

goroutine 205 [runnable]:
fmt.(*pp).handleMethods(0xc0009da000, 0x64, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/fmt/print.go:580 +0x6e
fmt.(*pp).printArg(0xc0009da000, 0x4a92980, 0xc0005a41a8, 0x64)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/fmt/print.go:699 +0x20a
fmt.(*pp).doPrintf(0xc0009da000, 0x4c1949b, 0x31, 0xc000473f28, 0x3, 0x3)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/fmt/print.go:1016 +0x158
fmt.Sprintf(0x4c1949b, 0x31, 0xc000d10f28, 0x3, 0x3, 0x400ae1c, 0xc000d10e18)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/fmt/print.go:214 +0x66
github.com/janelia-flyem/dvid/dvid.logUntimedMessage(0xc0005342a0, 0x4c1949b, 0x31, 0xc000d10f28, 0x3, 0x3)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/dvid/log.go:123 +0x63
github.com/janelia-flyem/dvid/dvid.Infof(0x4c1949b, 0x31, 0xc000d10f28, 0x3, 0x3)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/dvid/log.go:159 +0xa3
github.com/janelia-flyem/dvid/storage.DeleteDataInstance(0x4dd0e80, 0xc00048e5a0, 0xc0005a405b, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/storage/storage_local.go:396 +0x228
github.com/janelia-flyem/dvid/datastore.(*repoManager).deleteRepo.func1(0x4dd0e80, 0xc00048e5a0)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/datastore/repo_local.go:917 +0x39
created by github.com/janelia-flyem/dvid/datastore.(*repoManager).deleteRepo
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/datastore/repo_local.go:916 +0x1fa

goroutine 155 [select]:
github.com/valyala/gorpc.serverHandleConnection(0xc000959b20, 0xd400008, 0xc000010018, 0xc0005a4050, 0xb, 0xc000db4240)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:277 +0x525
created by github.com/valyala/gorpc.serverHandler
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:221 +0x289

goroutine 156 [IO wait]:
internal/poll.runtime_pollWait(0xa260dd8, 0x72, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000dd8018, 0x72, 0x0, 0x0, 0x4bec03e)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000dd8000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc000dd8000, 0xc0000e45a0, 0xbf6a559333445038, 0x6540bdb)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000dda000, 0x55610a0, 0xc000d16f00, 0x486bc99)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000dda000, 0x0, 0x1, 0xc0000e2ba0, 0xc000d16fc8)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/tcpsock.go:260 +0x48
github.com/valyala/gorpc.(*defaultListener).Accept(0xc000c6db20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/transport.go:74 +0x37
github.com/valyala/gorpc.serverHandler.func1(0xc000959b20, 0xc000d8e090, 0xc000d8e0a0, 0xc000d8e0b0, 0xc000d8e0c0, 0xc000460000)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:192 +0x38
created by github.com/valyala/gorpc.serverHandler
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:191 +0x150

goroutine 206 [runnable]:
github.com/janelia-flyem/dvid/datastore.(*repoManager).deleteRepo.func1(0x4dd1180, 0xc000a54940)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/datastore/repo_local.go:916
created by github.com/janelia-flyem/dvid/datastore.(*repoManager).deleteRepo
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/datastore/repo_local.go:916 +0x1fa

goroutine 94 [IO wait]:
internal/poll.runtime_pollWait(0xa260b68, 0x72, 0xffffffffffffffff)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0009ba098, 0x72, 0x10000, 0x10000, 0xffffffffffffffff)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0009ba080, 0xc0007fa000, 0x10000, 0x10000, 0x0, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_unix.go:169 +0x1f2
net.(*netFD).Read(0xc0009ba080, 0xc0007fa000, 0x10000, 0x10000, 0x0, 0x4a26620, 0x196)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010018, 0xc0007fa000, 0x10000, 0x10000, 0x0, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/net.go:177 +0x69
github.com/valyala/gorpc.(*readerCounter).Read(0xc00057a100, 0xc0007fa000, 0x10000, 0x10000, 0x4338221, 0x4a93e20, 0xc00057a148)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/conn_stats.go:118 +0x55
bufio.(*Reader).fill(0xc000dd4000)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadByte(0xc000dd4000, 0x196, 0x4c, 0x18)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/bufio/bufio.go:249 +0x39
compress/flate.(*decompressor).moreBits(0xc00014f300, 0x4a26620, 0xc0004602a6)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/compress/flate/inflate.go:696 +0x37
compress/flate.(*decompressor).nextBlock(0xc00014f300)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/compress/flate/inflate.go:303 +0x36
compress/flate.(*decompressor).Read(0xc00014f300, 0xc000ee8000, 0x10000, 0x10000, 0x6000600060006, 0x30, 0xb1704b8)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/compress/flate/inflate.go:347 +0x77
bufio.(*Reader).Read(0xc000dd4060, 0xc0005a4060, 0x1, 0x9, 0x1, 0x3, 0xc00004ef70)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x4d9f940, 0xc000dd4060, 0xc0005a4060, 0x1, 0x9, 0x1, 0xc000d28400, 0x3, 0xc00004ef70)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/io/io.go:310 +0x88
io.ReadFull(...)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/io/io.go:329
encoding/gob.decodeUintReader(0x4d9f940, 0xc000dd4060, 0xc0005a4060, 0x9, 0x9, 0x4015c75, 0xc000db4250, 0xc0005addf8, 0x402da3f)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/encoding/gob/decode.go:120 +0x70
encoding/gob.(*Decoder).recvMessage(0xc0009ba100, 0xc0005ade10)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/encoding/gob/decoder.go:81 +0x57
encoding/gob.(*Decoder).decodeTypeSequence(0xc0009ba100, 0x4c6ca00, 0xc0009ba100)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/encoding/gob/decoder.go:143 +0x12c
encoding/gob.(*Decoder).DecodeValue(0xc0009ba100, 0x4a267a0, 0xc00057a140, 0x16, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/encoding/gob/decoder.go:211 +0xf6
encoding/gob.(*Decoder).Decode(0xc0009ba100, 0x4a267a0, 0xc00057a140, 0xc000dbc000, 0xc000038180)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/encoding/gob/decoder.go:188 +0x191
github.com/valyala/gorpc.(*messageDecoder).Decode(...)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/encoding.go:100
github.com/valyala/gorpc.serverReader(0xc000959b20, 0x6766990, 0xc000010018, 0xc0005a4050, 0xb, 0xc000dbc000, 0xc000038180, 0xc0000381e0, 0x3601, 0xc000db4240)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:336 +0x199
created by github.com/valyala/gorpc.serverHandleConnection
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:272 +0x3ad

goroutine 95 [runnable]:
bufio.NewWriterSize(...)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/bufio/bufio.go:560
github.com/valyala/gorpc.newMessageEncoder(0x4da0ce0, 0xc000010018, 0x10000, 0x556d601, 0xc000959b80, 0x1000204040a94)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/encoding.go:76 +0x23a
github.com/valyala/gorpc.serverWriter(0xc000959b20, 0x4da0ce0, 0xc000010018, 0xc0005a4050, 0xb, 0xc000dbc000, 0xc000038180, 0xc000038240, 0x3601)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:417 +0xa3
created by github.com/valyala/gorpc.serverHandleConnection
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:275 +0x46c

goroutine 164 [IO wait]:
internal/poll.runtime_pollWait(0xa260d08, 0x72, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000bac518, 0x72, 0x0, 0x0, 0x4bec03e)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000bac500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc000bac500, 0x4b573c0, 0x50, 0xc00016a320)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000bf02b0, 0xc0004ba400, 0x6500d98, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc000bf02b0, 0x400e778, 0x30, 0x4b573c0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/tcpsock.go:247 +0x48
net/http.tcpKeepAliveListener.Accept(0xc000bf02b0, 0x4b573c0, 0xc000be9320, 0x4aa7740, 0x554bee0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/http/server.go:3264 +0x2f
net/http.(*Server).Serve(0xc000c01380, 0x4db7cc0, 0xc000bf02b0, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/http/server.go:2859 +0x22d
net/http.(*Server).ListenAndServe(0xc000c01380, 0xc000c01380, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/http/server.go:2797 +0xe4
net/http.ListenAndServe(0x4beafbd, 0x5, 0x0, 0x0, 0x0, 0xc000399da0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/http/server.go:3037 +0x74
created by main.DoServe
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/cmd/dvid/main.go:326 +0x7aa

goroutine 165 [IO wait]:
internal/poll.runtime_pollWait(0xa260ea8, 0x72, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0009bb518, 0x72, 0x0, 0x0, 0x4bec03e)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0009bb500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc0009bb500, 0xc000472d70, 0xc070b12a5a, 0xc00006d400)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000bbe550, 0x26bfe70b12a5a, 0x100000001, 0xc000472db0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc000bbe550, 0xc000472dd8, 0x40b49e6, 0x5dc8def9)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/tcpsock.go:247 +0x48
net/http.tcpKeepAliveListener.Accept(0xc000bbe550, 0xc000472e28, 0x18, 0xc000d26f00, 0x42dc2c4)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/http/server.go:3264 +0x2f
net/http.(*Server).Serve(0xc000bdc8f0, 0x4db7cc0, 0xc000bbe550, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/http/server.go:2859 +0x22d
net/http.(*Server).ListenAndServe(0xc000bdc8f0, 0xc000bdc8f0, 0x1)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/net/http/server.go:2797 +0xe4
github.com/janelia-flyem/dvid/server.serveHTTP()
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/server/web.go:589 +0x1be
created by github.com/janelia-flyem/dvid/server.Serve
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/server/server_local.go:500 +0x35e

goroutine 166 [semacquire]:
sync.runtime_Semacquire(0xc000959bf8)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc000959bf0)
	/miniforge/conda-bld/dvid_1559799187361/_build_env/go/src/sync/waitgroup.go:130 +0x65
github.com/valyala/gorpc.(*Server).Serve(0xc000959b20, 0xc000c659e0, 0xc0000c69a0)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:177 +0x64
github.com/janelia-flyem/dvid/rpc.StartServer(0xc0000c69a0, 0x5, 0x0, 0x0)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/rpc/server.go:183 +0x14d
github.com/janelia-flyem/dvid/server.Serve.func1()
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/server/server_local.go:504 +0x3d
created by github.com/janelia-flyem/dvid/server.Serve
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/janelia-flyem/dvid/server/server_local.go:503 +0x376

goroutine 214 [select]:
github.com/valyala/gorpc.serverHandler(0xc000959b20, 0xc000db4240)
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:200 +0x1d7
created by github.com/valyala/gorpc.(*Server).Start
	/miniforge/conda-bld/dvid_1559799187361/work/src/github.com/valyala/gorpc/server.go:158 +0x357
```

</details>

**Comment by DocSavage** [comment]
It looks like you may be using a non-HEAD version of master?  The panic says the repo deletion is in a different line than the current position, and there was a recent patch that fixed mismatched full unlock on a read lock (commit fc11fb).  Could you make sure you are using most recent code version and let me know if there's still a problem?  Thanks!

**Comment by DocSavage** [comment]
So if you are using the release version, this could be a problem, so we should just issue a new release.
